version: "2.4"
services:
  auth_service:
    image: 289116546479.dkr.ecr.us-east-1.amazonaws.com/auth_service:latest
    ports:
      - "5001:5001"
    networks:
      - bookstore_network
    mem_limit: 512M # Memory limit
    restart: on-failure
    #No Deploy Section

  catalog_service:
    image: 289116546479.dkr.ecr.us-east-1.amazonaws.com/catalog_service:latest
    ports:
      - "5003:5003"
    networks:
      - bookstore_network
    mem_limit: 768M
    restart: on-failure
    #No Deploy Section

  purchase_service:
    image: 289116546479.dkr.ecr.us-east-1.amazonaws.com/purchase_service:latest
    ports:
      - "5002:5002"
    networks:
      - bookstore_network
    mem_limit: 1024M
    restart: on-failure
    #No Deploy Section

  client: # This is where your load balancer will forward traffic to.
    image: 289116546479.dkr.ecr.us-east-1.amazonaws.com/client:latest
    ports:
      - "80:5000" # Host port 80 (or 443 for HTTPS) to container port 5000
    networks:
      - bookstore_network
    depends_on:
      - auth_service
      - catalog_service
      - purchase_service
    mem_limit: 512M
    restart: on-failure
    #No Deploy Section

networks:
  bookstore_network:
    driver: overlay